apiVersion: v1
kind: Service
metadata:
  name: {{ include "umbrella.fullname" . }}-fraud-service
  labels:
    {{- include "umbrella.labels" . | nindent 4 }}
    app.kubernetes.io/component: fraud-service
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.fraudService.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "umbrella.name" . }}
    app.kubernetes.io/component: fraud-service
    app.kubernetes.io/instance: {{ .Release.Name }}
