{{- range $component := list "transaction-service" "ledger-service" "fraud-service" "reconciliation-service" "notification-service" "api-gateway" }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "umbrella.fullname" $ }}-{{ $component }}
  labels:
    {{- include "umbrella.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ $component }}
  annotations:
    {{- with $.Values.linkerd.enabled }}
    {{- if . }}
    linkerd.io/inject: enabled
    {{- end }}
    {{- end }}
automountServiceAccountToken: false
{{- end }}
---
# Migrate SA already defined in serviceaccount-migrate.yaml with automount false, keep for Flyway Job
