apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "umbrella.fullname" . }}-migrate
  labels:
    {{- include "umbrella.labels" . | nindent 4 }}
    app.kubernetes.io/component: migrate
automountServiceAccountToken: false
