apiVersion: v1
kind: Secret
metadata:
  name: vault-token
  namespace: transaction-engine
stringData:
  token: root # dev only; prod uses approle / k8s auth
---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-backend
spec:
  provider:
    vault:
      server: http://vault.transaction-engine.svc.cluster.local:8200
      path: secret
      version: v2
      auth:
        tokenSecretRef:
          name: vault-token
          key: token
          namespace: transaction-engine
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: transaction-app-password
  namespace: transaction-engine
spec:
  refreshInterval: 1h
  secretStoreRef: { name: vault-backend, kind: ClusterSecretStore }
  target: { name: transaction-app-password, creationPolicy: Owner }
  data:
    - secretKey: DB_PASSWORD
      remoteRef: { key: secret/transaction-app, property: DB_PASSWORD }
    - secretKey: REDIS_PASSWORD
      remoteRef: { key: secret/redis, property: REDIS_PASSWORD }
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: customer-note-transit
  namespace: transaction-engine
spec:
  refreshInterval: 1h
  secretStoreRef: { name: vault-backend, kind: ClusterSecretStore }
  target: { name: customer-note-transit, creationPolicy: Owner }
  data:
    - secretKey: transit-key
      remoteRef: { key: transit/keys/customer-note }
